modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "mewdeko"
    version = "${version}"
    displayName = "MewdekoMC"
    description = "Bridges your NeoForge server with the Mewdeko Discord bot."

[[dependencies.mewdeko]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.mewdeko]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "SERVER"
