name: MewdekoMC
version: "${version}"
main: tech.mewdeko.mc.MewdekoPlugin
api-version: "1.21"
description: Companion plugin for the Mewdeko Discord bot
authors:
  - SylveonDeko
website: https://mewdeko.tech
